import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import {
  BUNDLED_PROVIDER_ACTIVATION_PROFILE_IDS,
  PROVIDER_ACTIVATION_PROFILES,
} from "../src/provider-activation-profiles.js";
import { generateProviderActivationProfiles } from "../../../scripts/generate-provider-activation-profiles.mjs";

const repositoryRoot = path.resolve(import.meta.dirname, "../../..");
const sourceRelativePath = "policy/provider-activation-profiles.v1.json";
const typescriptRelativePath =
  "packages/contracts/src/provider-activation-profiles.ts";
const swiftRelativePath =
  "native/macos/Sources/RecursBrokerCore/GeneratedProviderActivationProfiles.swift";
const priorTypescript = "prior typescript output\n";
const priorSwift = "prior swift output\n";
const invalidSourceError = new Error(
  "Invalid provider activation profile source",
);
const canonicalSource = `{
  "schemaVersion": 1,
  "profiles": [
    {
      "id": "anthropic_api_v1",
      "bundledProviderId": "anthropic-api"
    },
    {
      "id": "custom_openai_compatible_v1",
      "bundledProviderId": null
    },
    {
      "id": "kimi_code_v1",
      "bundledProviderId": "kimi-code"
    },
    {
      "id": "openai_api_v1",
      "bundledProviderId": "openai-api"
    }
  ]
}
`;
const canonicalSwift = `// Generated by scripts/generate-provider-activation-profiles.mjs. Do not edit.

package enum ProviderActivationProfileID: String, Codable, Hashable, CaseIterable, Sendable {
  case anthropicApiV1 = "anthropic_api_v1"
  case customOpenaiCompatibleV1 = "custom_openai_compatible_v1"
  case kimiCodeV1 = "kimi_code_v1"
  case openaiApiV1 = "openai_api_v1"

  package var bundledProviderID: String? {
    switch self {
    case .anthropicApiV1:
      "anthropic-api"
    case .customOpenaiCompatibleV1:
      nil
    case .kimiCodeV1:
      "kimi-code"
    case .openaiApiV1:
      "openai-api"
    }
  }
}
`;

const temporaryDirectories: string[] = [];

async function temporaryRoot(source: string | null = canonicalSource): Promise<string> {
  const root = await mkdtemp(path.join(os.tmpdir(), "recurs-provider-profiles-"));
  temporaryDirectories.push(root);
  if (source !== null) {
    await mkdir(path.join(root, "policy"), { recursive: true });
    await writeFile(path.join(root, sourceRelativePath), source, "utf8");
  }
  return root;
}

async function installPriorOutputs(root: string) {
  const typescriptPath = path.join(root, typescriptRelativePath);
  const swiftPath = path.join(root, swiftRelativePath);
  await Promise.all([
    mkdir(path.dirname(typescriptPath), { recursive: true }),
    mkdir(path.dirname(swiftPath), { recursive: true }),
  ]);
  await Promise.all([
    writeFile(typescriptPath, priorTypescript, "utf8"),
    writeFile(swiftPath, priorSwift, "utf8"),
  ]);
  return { typescriptPath, swiftPath };
}

afterEach(async () => {
  await Promise.all(
    temporaryDirectories.splice(0).map(async (directory) =>
      rm(directory, { force: true, recursive: true }),
    ),
  );
});

describe("provider activation profile generation", () => {
  it("exports one exact frozen cross-language identity catalog", async () => {
    const sourceText = await readFile(
      path.join(repositoryRoot, sourceRelativePath),
      "utf8",
    );
    const swift = await readFile(
      path.join(repositoryRoot, swiftRelativePath),
      "utf8",
    );

    expect(sourceText).toBe(canonicalSource);
    expect(PROVIDER_ACTIVATION_PROFILES).toEqual([
      { id: "anthropic_api_v1", bundledProviderId: "anthropic-api" },
      {
        id: "custom_openai_compatible_v1",
        bundledProviderId: null,
      },
      { id: "kimi_code_v1", bundledProviderId: "kimi-code" },
      { id: "openai_api_v1", bundledProviderId: "openai-api" },
    ]);
    expect(Object.isFrozen(PROVIDER_ACTIVATION_PROFILES)).toBe(true);
    expect(
      PROVIDER_ACTIVATION_PROFILES.every((profile) => Object.isFrozen(profile)),
    ).toBe(true);
    expect(BUNDLED_PROVIDER_ACTIVATION_PROFILE_IDS).toEqual({
      "anthropic-api": "anthropic_api_v1",
      "kimi-code": "kimi_code_v1",
      "openai-api": "openai_api_v1",
    });
    expect(Object.isFrozen(BUNDLED_PROVIDER_ACTIVATION_PROFILE_IDS)).toBe(true);
    expect(BUNDLED_PROVIDER_ACTIVATION_PROFILE_IDS).not.toHaveProperty(
      "custom-openai-compatible",
    );
    expect(swift).toBe(canonicalSwift);

    for (const id of PROVIDER_ACTIVATION_PROFILES.map(({ id }) => id)) {
      expect(swift).toContain(`= "${id}"`);
    }
    expect(swift).toContain(
      "enum ProviderActivationProfileID: String, Codable, Hashable, CaseIterable, Sendable",
    );
    expect(swift).toContain("var bundledProviderID: String?");
    expect(swift).not.toMatch(/endpoint|route|header|billing|wire/iu);
  });

  it("generates deterministic TypeScript and Swift and checks without writes", async () => {
    const root = await temporaryRoot();
    expect(
      await generateProviderActivationProfiles({ rootDirectory: root, check: true }),
    ).toBe(false);
    expect(
      await generateProviderActivationProfiles({ rootDirectory: root, check: false }),
    ).toBe(true);

    const typescriptPath = path.join(root, typescriptRelativePath);
    const swiftPath = path.join(root, swiftRelativePath);
    const first = await Promise.all([
      readFile(typescriptPath, "utf8"),
      readFile(swiftPath, "utf8"),
    ]);
    await generateProviderActivationProfiles({ rootDirectory: root, check: false });
    expect(await Promise.all([
      readFile(typescriptPath, "utf8"),
      readFile(swiftPath, "utf8"),
    ])).toEqual(first);

    await writeFile(typescriptPath, "drift\n", "utf8");
    expect(
      await generateProviderActivationProfiles({ rootDirectory: root, check: true }),
    ).toBe(false);
    expect(await readFile(typescriptPath, "utf8")).toBe("drift\n");
    expect(await readFile(swiftPath, "utf8")).toBe(first[1]);
  });

  it("stages every output before replacing any generated file", async () => {
    const root = await temporaryRoot();
    const blockedParent = path.join(root, "native/macos/Sources/RecursBrokerCore");
    await mkdir(path.dirname(blockedParent), { recursive: true });
    await writeFile(blockedParent, "not a directory", "utf8");

    await expect(
      generateProviderActivationProfiles({ rootDirectory: root, check: false }),
    ).rejects.toThrowError(new Error("Provider activation profile generation failed"));
    await expect(access(path.join(root, typescriptRelativePath))).rejects.toThrow();
  });

  it("restores every prior output when a later replacement fails", async () => {
    const root = await temporaryRoot();
    const { typescriptPath, swiftPath } = await installPriorOutputs(root);

    let replacements = 0;
    const renameFile = async (source: string, destination: string) => {
      if (source.endsWith(".tmp")) {
        replacements += 1;
        if (replacements === 2) {
          throw new Error("injected replacement failure");
        }
      }
      await rename(source, destination);
    };

    await expect(
      generateProviderActivationProfiles(
        { rootDirectory: root, check: false },
        { renameFile },
      ),
    ).rejects.toThrowError(
      new Error("Provider activation profile generation failed"),
    );
    expect(replacements).toBe(2);
    expect(await readFile(typescriptPath, "utf8")).toBe(priorTypescript);
    expect(await readFile(swiftPath, "utf8")).toBe(priorSwift);

    const artifacts = (
      await Promise.all([
        readdir(path.dirname(typescriptPath)),
        readdir(path.dirname(swiftPath)),
      ])
    ).flat().filter((name) => name.endsWith(".tmp") || name.endsWith(".bak"));
    expect(artifacts).toEqual([]);
  });

  it("retains a prior backup when rollback restoration fails", async () => {
    const root = await temporaryRoot();
    const { typescriptPath, swiftPath } = await installPriorOutputs(root);

    let replacements = 0;
    const renameFile = async (source: string, destination: string) => {
      if (source.endsWith(".tmp")) {
        replacements += 1;
        if (replacements === 2) {
          throw new Error("injected replacement failure");
        }
      }
      if (source.endsWith(".bak") && destination === swiftPath) {
        throw new Error("injected restoration failure");
      }
      await rename(source, destination);
    };

    await expect(
      generateProviderActivationProfiles(
        { rootDirectory: root, check: false },
        { renameFile },
      ),
    ).rejects.toThrowError(
      new Error("Provider activation profile generation failed"),
    );
    expect(await readFile(typescriptPath, "utf8")).toBe(priorTypescript);
    await expect(access(swiftPath)).rejects.toThrow();

    const backups = (await readdir(path.dirname(swiftPath)))
      .filter((name) => name.endsWith(".bak"));
    expect(backups).toHaveLength(1);
    expect(await readFile(path.join(path.dirname(swiftPath), backups[0]!), "utf8"))
      .toBe(priorSwift);
  });

  it.each([
    ["missing", null],
    ["malformed", "{"],
    ["noncanonical", JSON.stringify(JSON.parse(canonicalSource))],
    [
      "duplicate",
      `${JSON.stringify({
        schemaVersion: 1,
        profiles: [
          { id: "openai_api_v1", bundledProviderId: "openai-api" },
          { id: "openai_api_v1", bundledProviderId: "other-api" },
        ],
      }, null, 2)}\n`,
    ],
    [
      "unsorted",
      `${JSON.stringify({
        schemaVersion: 1,
        profiles: [
          { id: "openai_api_v1", bundledProviderId: "openai-api" },
          { id: "anthropic_api_v1", bundledProviderId: "anthropic-api" },
        ],
      }, null, 2)}\n`,
    ],
    [
      "unversioned",
      `${JSON.stringify({
        schemaVersion: 1,
        profiles: [
          { id: "openai_api", bundledProviderId: "openai-api" },
        ],
      }, null, 2)}\n`,
    ],
    [
      "65-byte profile id",
      `${JSON.stringify({
        schemaVersion: 1,
        profiles: [
          { id: `${"a".repeat(62)}_v1`, bundledProviderId: null },
        ],
      }, null, 2)}\n`,
    ],
    [
      "colliding Swift symbols",
      `${JSON.stringify({
        schemaVersion: 1,
        profiles: [
          { id: "foo_b1_v1", bundledProviderId: null },
          { id: "foo_b_1_v1", bundledProviderId: null },
        ],
      }, null, 2)}\n`,
    ],
  ])("rejects %s input with one fixed non-disclosing error", async (_label, source) => {
    const root = await temporaryRoot(source);

    await expect(
      generateProviderActivationProfiles({ rootDirectory: root, check: false }),
    ).rejects.toThrowError(invalidSourceError);
  });
});
