// Generated by scripts/generate-provider-activation-profiles.mjs. Do not edit.

export const PROVIDER_ACTIVATION_PROFILES = Object.freeze([
  Object.freeze({"id":"anthropic_api_v1","bundledProviderId":"anthropic-api"}),
  Object.freeze({"id":"custom_openai_compatible_v1","bundledProviderId":null}),
  Object.freeze({"id":"kimi_code_v1","bundledProviderId":"kimi-code"}),
  Object.freeze({"id":"openai_api_v1","bundledProviderId":"openai-api"}),
] as const);

export type ProviderActivationProfileId =
  (typeof PROVIDER_ACTIVATION_PROFILES)[number]["id"];

export const BUNDLED_PROVIDER_ACTIVATION_PROFILE_IDS = Object.freeze({
  "anthropic-api": "anthropic_api_v1",
  "kimi-code": "kimi_code_v1",
  "openai-api": "openai_api_v1",
} as const);
