// Generated by scripts/generate-provider-activation-profiles.mjs. Do not edit.

package enum ProviderActivationProfileID: String, Codable, Hashable, CaseIterable, Sendable {
  case anthropicApiV1 = "anthropic_api_v1"
  case customOpenaiCompatibleV1 = "custom_openai_compatible_v1"
  case kimiCodeV1 = "kimi_code_v1"
  case openaiApiV1 = "openai_api_v1"

  package var bundledProviderID: String? {
    switch self {
    case .anthropicApiV1:
      "anthropic-api"
    case .customOpenaiCompatibleV1:
      nil
    case .kimiCodeV1:
      "kimi-code"
    case .openaiApiV1:
      "openai-api"
    }
  }
}
