// Generated by scripts/generate-non-secret-policy.mjs. Do not edit.

package enum GeneratedNonSecretPolicy {
  package static let forbiddenNormalizedKeys: Set<String> = [
    "accesskey",
    "apikey",
    "arguments",
    "argv",
    "auth",
    "authorization",
    "cookie",
    "cookies",
    "credential",
    "credentials",
    "env",
    "environment",
    "filepath",
    "header",
    "headers",
    "password",
    "path",
    "privatekey",
    "secret",
    "secrets",
    "setting",
    "settings",
    "token",
    "tokens",
  ]

  package static let privateKeyBegin = "-----BEGIN "
  package static let privateKeySuffix = "PRIVATE KEY-----"
  package static let privateKeyLabelSeparator = " "

  package static let tokenPrefixes = [
    "AIza",
    "AKIA",
    "ASIA",
    "gho_",
    "ghp_",
    "ghr_",
    "ghs_",
    "ghu_",
    "github_pat_",
    "sk-",
    "sk-proj-",
    "xoxa-",
    "xoxb-",
    "xoxp-",
    "xoxr-",
    "xoxs-",
  ]
  package static let tokenMinimumSuffixLength = 16

  package static let jwtFirstSegmentPrefix = "eyJ"
  package static let jwtMinimumFirstRemainderLength = 10
  package static let jwtMinimumOtherSegmentLength = 10
  package static let jwtSegmentCount = 3

  package static let authorizationSchemes = [
    "Basic",
    "Bearer",
  ]
  package static let authorizationMinimumPayloadLength = 12
  package static let authorizationWhitespaceCodePoints: Set<UInt32> = [
    9,
    10,
    11,
    12,
    13,
    32,
    160,
    5760,
    8192,
    8193,
    8194,
    8195,
    8196,
    8197,
    8198,
    8199,
    8200,
    8201,
    8202,
    8232,
    8233,
    8239,
    8287,
    12288,
    65279,
  ]

  package static let longHexMinimumLength = 48
  package static let mixedEntropyMinimumLength = 48
  package static let mixedEntropyMinimumDistinctCharacters = 12
}
